version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:

      - echo "Building application..."
      - npm run build
    env:
      variables:
        NODE_OPTIONS: "--max-old-space-size=2048"
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - dist/**/*
    - node_modules/**/*
  name: BuildArtifact

cache:
  paths:
    - node_modules/**/*